name: Dev deploy # Workflow 이름
on: # Event 감지
  push:
    branches:
      - develop
jobs: # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2

      - name: Check Node v # Node v 확인
        run: node -v

      - name: Install Dependencies # 의존 파일 설치
        run: yarn install --frozen-lockfile

      - name: Build # React Build
        run: yarn build

      - name: Deploy # Upload build file to S3
        env:
          CI: false
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: $ {{ secrets.SECRET_ACCESS_KEY }}
        run: aws s3 cp --recursive --region ap-northeast-2 build s3://petition-bucket
